### ISSUE TITLE
fakecam 3 does not start

### ISSUE THREAD

**Issue by damnms** [diddlesnaps/fakecam#17]
ubuntu 20.10

```
oli@lucy:~$ fakecam.gui 
Traceback (most recent call last):
  File "/snap/fakecam/110/bin/fakecamgui", line 33, in <module>
    sys.exit(load_entry_point('Fakecam==3.0.0', 'console_scripts', 'fakecamgui')())
  File "/snap/fakecam/110/lib/python3.6/site-packages/fakecam/gui.py", line 12, in main
    MainWindow()
  File "/snap/fakecam/110/lib/python3.6/site-packages/fakecam/ui/mainwindow.py", line 126, in __init__
    video_source.set_active(devices.index(self.camera))
ValueError: '/dev/video0' is not in list
oli@lucy:~$ ls /dev/video
video0  video1  video2  
```

**Comment by diddledan** [comment]
Thanks for the report. I think I've fixed it. Could you try again?

**Comment by damnms** [comment]
can not test it because the download is very very slow and stalls at about 80%
