### ISSUE TITLE
core20: Permission denied: '/sys/class/video4linux/video0/name'

### ISSUE THREAD

**Issue by Selaron** [diddlesnaps/fakecam#23]
When I compile and run the current core20 branch, I get "Permission denied: '/sys/class/video4linux/video0/name'".

/sys/class/video4linux/video0/name has read access for user/group/everyone.

I also have run "sudo snap connect fakecam:camera".

Any idea on how this can be fixed? Is snap somewhat limiting permissions here?

(fakecamgui:5155): GLib-GIO-WARNING **: 10:44:10.146: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Traceback (most recent call last):
  File "/snap/fakecam/x6/bin/fakecamgui", line 8, in <module>
    sys.exit(main())
  File "/snap/fakecam/x6/lib/python3.8/site-packages/fakecam/gui.py", line 12, in main
    MainWindow()
  File "/snap/fakecam/x6/lib/python3.8/site-packages/fakecam/ui/mainwindow.py", line 126, in __init__
    with open(os.path.join(v4ldir, os.path.basename(device), "name")) as name_file:
PermissionError: [Errno 13] Permission denied: '/sys/class/video4linux/video0/name'

**Comment by diddledan** [comment]
This access is provided by the `camera` interface. Please ensure it's connected - you can check with `snap connections fakecam`. Ideally you should not be building yourself if you are not developing the app, but should use the version from the store (the core20 branch is in the beta channel, but will be promoted once it's stabilised - install it with `sudo snap install fakecam --beta`).

**Comment by Selaron** [comment]
After installing the 3.0.0 beta (rev 112) it is still the same.

```
$ snap connections fakecam
Interface                 Plug                     Slot                             Notes
camera                    fakecam:camera           :camera                          manual
content[gnome-3-38-2004]  fakecam:gnome-3-38-2004  gnome-3-38-2004:gnome-3-38-2004  -
content[gtk-3-themes]     fakecam:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      fakecam:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     fakecam:sound-themes     gtk-common-themes:sound-themes   -
desktop                   fakecam:desktop          :desktop                         -
desktop-legacy            fakecam:desktop-legacy   :desktop-legacy                  -
gsettings                 fakecam:gsettings        :gsettings                       -
home                      fakecam:home             :home                            -
network                   fakecam:network          :network                         -
network-bind              fakecam:network-bind     :network-bind                    -
opengl                    fakecam:opengl           :opengl                          -
removable-media           fakecam:removable-media  :removable-media                 manual
wayland                   fakecam:wayland          :wayland                         -
x11                       fakecam:x11              :x11                             -

$ snap list
Name                    Version                     Rev    Tracking       Publisher   Notes
bare                    1.0                         5      latest/stable  canonical✓  base
core                    16-2.50                     11081  latest/stable  canonical✓  core
core18                  20210507                    2066   latest/stable  canonical✓  base
core20                  20210429                    1026   latest/stable  canonical✓  base
cuda-runtime-11-2-1804  11.2                        2      latest/stable  diddledan   -
fakecam                 3.0.0                       112    latest/beta    diddledan   -
gnome-3-28-1804         3.28.0-19-g98f9e67.98f9e67  145    latest/stable  canonical✓  -
gnome-3-34-1804         0+git.3556cb3               66     latest/stable  canonical✓  -
gnome-3-38-2004         0+git.3d25b9b               39     latest/stable  canonical✓  -
gtk-common-themes       0.1-52-gb92ac40             1515   latest/stable  canonical✓  -
multipass               1.7.0-dev.815+g8abacb79     4729   latest/edge    canonical✓  -
multipass-sshfs         1.1                         145    latest/edge    canonical✓  -
snap-store              3.38.0-59-g494f078          518    latest/stable  canonical✓  -
snapcraft               4.7.1                       6466   latest/stable  canonical✓  classic
snapd                   2.50                        11841  latest/stable  canonical✓  snapd

```
